run:
	cp .env.example .env
	cp frontend/.env.example frontend/.env
	cp backend/.env.example backend/.env
	cd frontend && npm install && cd ..
	cd backend && npm install && cd ..
	docker compose up 
	
